ingressController:
  enabled: true
  env:
    publish_service: kong/kong-dp-kong-proxy

image:
  repository: kong/kong
  tag: "3.9.1-ubuntu"

secretVolumes:
  - kong-cluster-cert

env:
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: demo123
  pg_host: kong-cp-db-rw.kong.svc.cluster.local
  pg_ssl: "on"
  pg_ssl_version: tlsv1_3
  # admin_gui_api_url: localhost:30786
  kong_vitals: on
  cluster_telemetry_listen: 0.0.0.0:8006

admin:
  enabled: true
  type: NodePort
  http:
    enabled: true
  # labels:
  #   enable-metrics: "true"

manager:
  enabled: true

cluster:
  enabled: true
  tls:
    enabled: true

proxy:
  enabled: false

# serviceMonitor:
#   enabled: true
